### ISSUE TITLE
request send payload

### ISSUE THREAD

**Issue by andrea-ap** [ChendoChap/pOOBs4#14]
I ask if possible at the end of the html code, which gives a waiting message, insert a code to inject a payload .bin file

**Comment by mc-17** [comment]
For now I wrote this - you can modify the payload https://github.com/mc-17/pspack-flask

**Comment by Khiu** [comment]
Or here:
https://github.com/KameleonReloaded/leeful900

**Comment by andrea-ap** [comment]
Ok, thanks
