### ISSUE TITLE
Select accound screen just  show beck ground

### ISSUE THREAD

**Issue by Bogdans29** [ChendoChap/pOOBs4#26]
Sometimes whan i boot from rest mode i get this screen need to hard restart ![20211224_190548.jpg](https://user-images.githubusercontent.com/44641106/147370890-130b200f-9f91-4820-a86d-7abba1ce4032.jpg) 
Ghen 2.0b/2.2.b

**Comment by ChendoChap** [comment]
This repository does not provide anything beyond the initial kernel patches that allow you to execute payloads.
If you encounter issues with certain payloads you should report your issues to the developers of those payloads through whatever means they make available to you.
