### ISSUE TITLE
What is This?

### ISSUE THREAD

**Issue by mohammad7800** [ChendoChap/pOOBs4#28]
![image](https://user-images.githubusercontent.com/42559776/147542407-05beb17a-6737-4c8b-befb-4a62e910b1de.png)
Does Ps4 browsers have log4j vulnerability ? Why are u trying to connect nsa.gov??  :|

**Comment by erwangse** [comment]
It's an easter egg IIRC

**Comment by dmiller423** [comment]
It's a joke ;sigh;  you need to open an issue to claim it's broken so you could post a screen shot of what we already know is there?
