### ISSUE TITLE
Question, not an issue.

### ISSUE THREAD

**Issue by Doyle4** [ChendoChap/pOOBs4#32]
I have spotted a Pico.img, can't see anything on it.

Is this for a Raspberry Pi Pico?

Thanks

**Comment by ChendoChap** [comment]
Not necessarily, it's just the tiniest image I could make, it is pretty much functionally identical to the original image.

**Comment by Doyle4** [comment]
Thanks for getting back.

thats pretty damn impressive, thanks for your work.
