### ISSUE TITLE
PS4 Fat won't sleep

### ISSUE THREAD

**Issue by therealsamsquanch** [ChendoChap/pOOBs4#37]
The jailbreak works as intended, but when I'm done playing and try to put the console on sleep mode, its white light keeps pulsing forever and it never goes orange, indicating that the console is sleeping. If I don't run the jailbreak, my PS4 can go in and out of sleep mode, no problems. Model is CUH-1001A.

**Comment by barisyild** [comment]
This is probably because of the payload (goldenhen, mirahen, etc) you are using.

**Comment by therealsamsquanch** [comment]
I think you're right.
