### ISSUE TITLE
notification didn't pop 

### ISSUE THREAD

**Issue by strepito66** [ChendoChap/pOOBs4#4]
So, i run the webkit, when it tells me to plug the usb i dot it, but then nothing happens, if i unplug the usb the ps4 crashes, and if I leave it there no "unsupported filesystem" notification pop

**Comment by Nando600** [comment]
Happens the same to me

**Comment by oneohthree** [comment]
Did you write the `img` file correctly? Did you try another USB drive.

**Comment by Nando600** [comment]
> Did you write the `img` file correctly? Did you try another USB drive.

Yes i did flash it correctly, and nothing happens or my ps4 shuts off aka kernel panic, I'm using Al Azif DNS and Host

**Comment by Ekaekale** [comment]
Same. I tried with 2 USB drive. I write the img with Win32Disk as showew in the readme file. My PS4 shuts off by itself whenever I'm plugging the USB after the "insert usb" ;;

**Comment by kerenon** [comment]
Same problem here. 9.00 PS4 Pro, fresh after factory reset. Tried 3 different usb sticks, tried writing the image with win32diskimager and from linux with dd. The results are always the same. Either nothing happens, or the console just shuts down shortly after plugging in the stick (tried all 3 ports).

**Comment by ClaudioVarandas** [comment]
Same here, day one PS4 FAT, after usb inserted starts loading then the console shutdown.

**Comment by ErnieBall** [comment]
I had the same issue, tried several Sticks, redownloaded the img, tried different imaging tools.

The 4th USB Stick i tried just worked, and keeps working stable.
Seems like this is a bit picky about what stick you use.

**Comment by Nando600** [comment]
> I had the same issue, tried several Sticks, redownloaded the img, tried different imaging tools.
> 
> The 4th USB Stick I tried just worked, and keeps working stable. Seems like this is a bit picky about what stick you use.

Alright but I don't have many USBs that I at least don't use or store important files on plus the fact of knowing once I do these steps I cannot format them to reuse them again as far as I understood otherwise I can sure go to my local hardware store and buy a type A 4GB stick for less than 5€ but since I don't know if they will work I am not so sure and I prefer to not waste money if possible

**Comment by rynho** [comment]
there was cases ppl download bad .img file.  make sure to get it from pBOOs4 github, should be 4MB.
