### ISSUE TITLE
Question intercept https

### ISSUE THREAD

**Issue by bbday** [ChendoChap/pOOBs4#40]
Question:
If i wanna intercept https or encrypted packets with proxy (you can setup on settings) how i can setup my cert on jailbreaked ps4? where to put .cert file?

Thanks

**Comment by dmiller423** [comment]
Can you tell me how this is an issue?
And you don't install a cert on a 'jailbreaked' ps4,  you'd have to accept an invalid cert when you visit.
Please don't open issues, for things that aren't an issue...

**Comment by bbday** [comment]
sorry but i wrote on topic is question, i found how do it.

**Comment by dmiller423** [comment]
You're failing to comprehend here...  
Opening an issue, is for issues with the code in the repository.
Not to ask for help if you're having trouble blowing your nose or using ftp.
