### ISSUE TITLE
is there supposed to be absolutely nothing on the drive after I format it

### ISSUE THREAD

**Issue by Zaccian** [ChendoChap/pOOBs4#43]
im trying to format the drive with the iso provided and the repository but im not sure if its supposed to read as a SFD, am i supposed to use the other with "pico" in its name?

("for context when i format it theres nothing on it im not sure if this is meant to be like that or if the iso i downloaded from the repo was bad or corrupted")

attached a video for better explanation

https://user-images.githubusercontent.com/58353017/155043233-249ab73c-f67b-4c6e-8be1-05981bc74c48.mp4

**Comment by dmiller423** [comment]
It is supposed to be like that,  did you try it ?

**Comment by Zaccian** [comment]
no i did not sorry!

**Comment by Zaccian** [comment]
i have a spare ps4 sitting around but to avoid it updating I'm gonna shut down all wifi in the house it will just take a bit

**Comment by dmiller423** [comment]
You could (and should) disable automatic updating,  if you have a decent router block the updates.

**Comment by Zaccian** [comment]
guess my aint decent

**Comment by Zaccian** [comment]
wait is it supposed to be assigned a drive letter? because when I do it with Rufus it gets a drive letter and I can read whats on it
