### ISSUE TITLE
Tutorial for Linux

### ISSUE THREAD

**Issue by nickcat325** [ChendoChap/pOOBs4#5]
If you are in Linux it's very easy to make a jailbreak usb. **Make sure you enter the path to usb and not something else.** You can find the root path to usb by doing `sudo fdisk -l` for a terminal lookup or `gparted` for gui. The **of** should look like /dev/sdb not /dev/sdb1 for example. **if** means input file and **of** means output file.
`sudo dd if=~/Downloads/exfathax.img of=/dev/(USB) status=progress`

**Comment by cuj** [comment]
Does this tutorial also apply to mac?
